[tool.black]
line-length = 90
experimental_string_processing = true

[tool.isort]
profile = 'black'
multi_line_output = 3

[tool.pytest.ini_options]
markers = [
    "memory: marks tests that are used for memory profiling",
]
