# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pytest

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - 3.9

    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
          pip install pytest-monitor
      - name: Install package
        run: |
          pip install .
      - name: Pytest
        env:
          CUDA_VISIBLE_DEVICES: -1
          TF_CPP_MIN_LOG_LEVEL: 3
          # this might be really dumb, but we have to suppress libcudart error
        run: |
          pytest -m "memory" ./CI/
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          echo "# Memory Scaling" >> report.md
          sqlite3 -header -markdown .pymon "SELECT * FROM TEST_METRICS" >> report.md
          cml-send-comment report.md