# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pytest

on:
  push:
  pull_request:

jobs:
  example-1:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - "ubuntu-latest"
        python-version:
          - "3.8"
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list
      - name: Install dependencies
        run: |
          conda install -c anaconda sqlite
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
          pip install pytest-monitor
      - name: Install package
        run: |
          pip install .
      - name: Pytest
        env:
          CUDA_VISIBLE_DEVICES: -1
          TF_CPP_MIN_LOG_LEVEL: 3
          # this might be really dumb, but we have to suppress libcudart error
        run: |
          pytest -m "memory" ./CI/
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          echo "# Memory Scaling" >> report.md
          sqlite3 -header -markdown .pymon "SELECT * FROM TEST_METRICS" >> report.md
          cml-send-comment report.md