name: pytest-memory profiling

on:
  push:
  pull_request:

jobs:
  memory-profiling:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.8"
          # Using conda for the newer version of sqlite that supports-markdown
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list
      - name: echo sqlite version
        run: |
          /usr/share/miniconda/envs/test/bin/sqlite3 --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
          pip install pytest-monitor
      - name: Install package
        run: |
          pip install .
      - name: Pytest
        env:
          CUDA_VISIBLE_DEVICES: -1
          TF_CPP_MIN_LOG_LEVEL: 3
          # this might be really dumb, but we have to suppress libcudart error
        run: |
          pytest -m "memory" ./CI/
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          /usr/share/miniconda/envs/test/bin/sqlite3 -header -csv .pymon "SELECT ITEM_VARIANT, MEM_USAGE, CPU_USAGE, USER_TIME FROM TEST_METRICS" >> data.csv
          # create a plot with pandas
          python -c "import pandas as pd; df = pd.read_csv('data.csv'); df = df.set_index('ITEM_VARIANT'); df.index = df.index.str.extract('(\d+)', expand=False).astype(int); df.plot().figure.savefig('plot.png')"
          echo "# Memory Scaling" >> report.md
          /usr/share/miniconda/envs/test/bin/sqlite3 -header -markdown .pymon "SELECT ITEM_VARIANT, MEM_USAGE, CPU_USAGE, USER_TIME FROM TEST_METRICS" >> report.md
          cml publish ./plot.png --md >> report.md
          cml-send-comment report.md